#pragma once

#define REG_SAVE         0x00
#define REG_CALSW        0x01
#define REG_RSW          0x02
#define REG_RRATE        0x03
#define REG_BAUD         0x04
#define REG_AXOFFSET     0x05
#define REG_AYOFFSET     0x06
#define REG_AZOFFSET     0x07
#define REG_GXOFFSET     0x08
#define REG_GYOFFSET     0x09
#define REG_GZOFFSET     0x0a
#define REG_HXOFFSET     0x0b
#define REG_HYOFFSET     0x0c
#define REG_HZOFFSET     0x0d
#define REG_D0MODE       0x0e
#define REG_D1MODE       0x0f
#define REG_D2MODE       0x10
#define REG_D3MODE       0x11
#define REG_D0PWMH       0x12
#define REG_D1PWMH       0x13
#define REG_D2PWMH       0x14
#define REG_D3PWMH       0x15
#define REG_D0PWMT       0x16
#define REG_D1PWMT       0x17
#define REG_D2PWMT       0x18
#define REG_D3PWMT       0x19
#define REG_IICADDR      0x1a
#define REG_LEDOFF       0x1b
#define REG_GPSBAUD      0x1c

#define REG_YYMM         0x30
#define REG_DDHH         0x31
#define REG_MMSS         0x32
#define REG_MS           0x33
#define REG_AX           0x34
#define REG_AY           0x35
#define REG_AZ           0x36
#define REG_GX           0x37
#define REG_GY           0x38
#define REG_GZ           0x39
#define REG_HX           0x3a
#define REG_HY           0x3b
#define REG_HZ           0x3c
#define REG_Roll         0x3d
#define REG_Pitch        0x3e
#define REG_Yaw          0x3f
#define REG_TEMP         0x40
#define REG_D0Status     0x41
#define REG_D1Status     0x42
#define REG_D2Status     0x43
#define REG_D3Status     0x44
#define REG_PressureL    0x45
#define REG_PressureH    0x46
#define REG_HeightL      0x47
#define REG_HeightH      0x48
#define REG_LonL         0x49
#define REG_LonH         0x4a
#define REG_LatL         0x4b
#define REG_LatH         0x4c
#define REG_GPSHeight    0x4d
#define REG_GPSYAW       0x4e
#define REG_GPSVL        0x4f
#define REG_GPSVH        0x50

#define REG_Q0 0x51
#define REG_Q1 0x52
#define REG_Q2 0x53
#define REG_Q3 0x54
      
#define DIO_MODE_AIN     0
#define DIO_MODE_DIN     1
#define DIO_MODE_DOH     2
#define DIO_MODE_DOL     3
#define DIO_MODE_DOPWM   4
#define DIO_MODE_GPS     5